basic.showString("Full Sender")
input.setAccelerometerRange(AcceleratorRange.EightG)
radio.setGroup(24)
basic.forever(function () {
    basic.pause(100)
    led.toggle(0, 0)
    radio.sendValue("dir", input.compassHeading())
    radio.sendValue("y", input.acceleration(Dimension.Y))
    radio.sendValue("x", input.acceleration(Dimension.X))
    radio.sendValue("z", input.acceleration(Dimension.Z))
})
