basic.showString("M sender")
input.setAccelerometerRange(AcceleratorRange.EightG)
radio.setGroup(24)
basic.forever(function () {
    radio.sendNumber(input.compassHeading())
    basic.showNumber(input.compassHeading())
    radio.sendNumber(input.acceleration(Dimension.Z))
    radio.sendNumber(input.acceleration(Dimension.X))
    radio.sendNumber(input.acceleration(Dimension.Y))
})
